# Generated by Django 6.0.3 on 2026-03-27 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('Reception', 'Reception'), ('Accounts', 'Accounts'), ('Procurement', 'Procurement'), ('HR', 'Human Resource'), ('Registry', 'Registry'), ('Technical', 'Technical')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
