# Generated by Django 6.0.3 on 2026-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', '--- Custom/General Message ---'), ('Internet interruption detected', 'Internet interruption detected'), ('Scheduled system maintenance', 'Scheduled system maintenance'), ('Power outage in server room', 'Power outage in server room'), ('Email service delays', 'Email service delays'), ('Services restored', 'Services restored')], default='General', help_text='Select a common issue to auto-fill.', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, help_text="Type date, time, or extra details here (e.g. 'on Friday at 2PM')."),
        ),
    ]
