# Generated by Django 6.0.3 on 2026-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_announcement_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('Reception', 'Reception'), ('Accounts', 'Accounts'), ('Procurement', 'Procurement'), ('HR', 'Human Resource'), ('Registry', 'Registry'), ('Technical', 'Technical')], default='ICT', max_length=50),
        ),
    ]
