# Generated by Django 6.0.3 on 2026-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_announcement_options_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
