# Generated by Django 6.0.3 on 2026-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('System Maintenance', 'System Maintenance'), ('Network Alert', 'Network Alert'), ('Security Update', 'Security Update'), ('Software Update', 'Software Update'), ('Holiday Notice', 'Holiday Notice')], default='General', max_length=100),
        ),
    ]
